### PR TITLE
Remove height on the tree-view-resizer

### PR DESCRIPTION
**Pull request by simurai**
:warning: This PR depends on https://github.com/atom/atom/pull/9274

This lets the `height` be changed by the parent flexbox added in https://github.com/atom/atom/pull/9274.

### CODE REVIEW

**Comment by simurai** [comment]
With https://github.com/atom/atom/commit/67964eaa8a45e21732ca8b6d6e4c9cad0f3da046, this PR is technically not needed anymore. But we can still merge this and maybe one day that "hack" isn't needed anymore.

**Comment by benogle** [comment]
These specs do not pass with current atom master.

**Comment by simurai** [comment]
> These specs do not pass with current atom master.

Are there specs in `atom/atom` that test with the tree-view package?

**Comment by simurai** [comment]
btw. this PR is not super urgent. Meaning, it shouldn't break anything if not merged. It's just to "clean up".

**Comment by thedaniel** [comment]
@benogle it's green for me on master...

**Comment by thedaniel** [comment]
Let's wait until the next stable has gone out and re-run this travis build on that.

**Comment by simurai** [comment]
Merged in `master` but still failing. I'll close this since it's not _that_ crucial (the `100%` gets overridden by core).

**Pull request closed without merging**
