### PR TITLE
Added functionality to focus parent folder on deletion

### LINKED ISSUE #60: Losing highlight focus on deletion of files/folders
When you delete a file in a directory using the hotkeys, it'd be nice if the highlight focus moved to the next file or at least to the top of the directory that you were in so that you don't have to click back to where you were or scroll all the way down using the arrows. Right now the highlight focus disappears so if you press the down arrow, the highlight starts back at the top of the directory

### PR DESCRIPTION
**Pull request by deiga**
Fixes #60

### CODE REVIEW

**Comment by johngeorgewright** [comment]
:+1:

I also think it maybe nice to focus on the previous sibling... and if there isn't one, the parent folder.

**Comment by benogle** [comment]
> I also think it maybe nice to focus on the previous sibling... and if there isn't one, the parent folder.

I agree with this. @deiga if you're still down for messing with this, I can guide it to merge. 

We'll also need a spec.

cc @atom/feedback

**Comment by deiga** [comment]
Yeah, sure! I'll look at getting a spec done :)

**Comment by thedaniel** [comment]
@deiga did you need help getting a spec going here?

**Comment by deiga** [comment]
@thedaniel possibly, yeah. I seem to be a bit short on time :P

**Pull request closed without merging**
