### PR TITLE
Don't open file on single-click unless core.allowPendingPaneItems=true

### PR DESCRIPTION
**Pull request by kuychaco**
Also cleaned up specs for when files are clicked. Removed unnecessary tests that cover behavior implemented in Atom core.

/cc @BinaryMuse

### CODE REVIEW

**Comment by Alhadis** [comment]
May I ask the reasons why this was done?

I barely upgraded 10 minutes ago and the need to double-click everything all of a sudden is already driving me crazy...

**Comment by kuychaco** [comment]
@Alhadis #199 contains the discussion leading to this change

**Comment by Alhadis** [comment]
Ah, I see.

Would you consider having a user-setting to keep the old behaviour? I'm happy to submit the PR. =)

**Comment by vemv** [comment]
* I want keep opening files with a single click, as I've done with Atom for a couple years
* I don't want to set `allowPendingPaneItems = true`, it's not a feature of my liking (it was recently introduced - it's not like it's a traditional Atom feature)
* Furthermore two totally different things (allowPendingPaneItems, open-on-single-click) shouldn't be conflated. Please add a separate option instead: openOnSingleClick.

**Please stop breaking everyone's workflow**. Atom does this a few times a year. Pretty much barbaric.

**Comment by Alhadis** [comment]
@vemv Couldn't agree more, which is why I [submitted a PR for this](https://github.com/atom/tree-view/pull/804).

**Pull request merged**
