### PR TITLE
Use getFullExtension instead of path.extname in dialogs

### LINKED ISSUE #838: Provide a more accurate file extension matching through grammars
Recently I've started to refactor a lot of Blade template files, which have extension `.blade.php`. Renaming such files is slightly inconvenient because if I were to rename a file called `somefile.blade.php`, it would automatically select `somefile.blade` for me, I would quickly start typing and then lose the `.blade` suffix -- this forces me to override the suggested selection or re-type it.

I figured it would be rather neat if we could attempt matching the longest file extension from the available grammars and select the base file name based on that first. If there aren't any matches, then revert to old behavior.

Currently I am leaving this here as an idea, but I might eventually submit a pull request, unless someone else wants to do this.

### PR DESCRIPTION
**Pull request by Ingramz**
Closes #838 

If we need a test for this, then I need some guidance regarding how to approach. And also the current test will only work because the file names used for testing already give the full extension using `path.extname`.

### CODE REVIEW

**Comment by 50Wliu** [comment]
For specs, you could create a related spec that tests with a multi-extension file.  For example,
```coffee
it "recognizes multi-extension files", ->
  dotFilePath = path.join(dirPath, "test.file.txt")
  expect(moveDialog).toExist()
  expect(moveDialog.miniEditor.getText()).toBe(atom.project.relativize(dotFilePath))
  expect(moveDialog.miniEditor.getModel().getSelectedText()).toBe "test"
```

**Comment by Ingramz** [comment]
@50Wliu alright, thanks. I'll work on this and also add related tests for `getFullExtension`.

**Comment by 50Wliu** [comment]
> and also add related tests for `getFullExtension`.

Don't worry about this unless you really have nothing else to do :).  I added that helper, I should probably be the person writing tests for it.

**Comment by 50Wliu** [comment]
@Ingramz are you still interested in finishing this PR?  All it needs is that extra spec.

**Comment by Ingramz** [comment]
@50Wliu I'll probably get to it sometime next week.

**Pull request closed without merging**
