### PR TITLE
:bug: Fix transparent dragging background with themes

### PR DESCRIPTION
**Pull request by forivall**
On my theme, since the background of individual tree view icons have a transparent background, the drag indicator is unreadable. This fixes that issue. I can provide a gif upon request. I'm also fine with documenting the regex, since it is kinda hairy.

### CODE REVIEW

**Comment by benogle** [comment]
Please provide a gif :heart:

**Comment by forivall** [comment]
without fix:
without fix
with fix:
with fix

**Comment by 50Wliu** [comment]
@forivall Sorry for the very delayed reply.  Is this still an issue?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/pull/565#issuecomment-332038520. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Pull request closed without merging**
