### PR TITLE
Alphabetical tree-view sorting (files and directories mixed together, Mac OS X finder style)

### PR DESCRIPTION
**Pull request by mscottford**
An experimental implementation for addressing #64, and perhaps a path towards addressing #235.

I thought I would open the conversation about this approach before I take the time to:

- [x] add a configuration parameter alphabetical sorting
- [x] create specs
- [x] search for odd edge cases

tree-sort-demo

### CODE REVIEW

**Comment by thedaniel** [comment]
Since this is the way Finder does it when you sort by name, would you expect the tree-view on OS X to match it out of the box? If so, we would need to decide how to set the defaults on the other two platforms as well.

**Comment by thedaniel** [comment]
I think my preference would be to leave it as it is by default but provide this option, and/or possibly add it to the context menu on the top-level tree item.

**Comment by mscottford** [comment]
I think it's okay to have alphabetical sorting be the default, since that's the current behavior. And it's the current behavior of similar text editors. Textmate is the only one I can think of off the top of my head that sorted it's tree view using "Finder style".

**Comment by thedaniel** [comment]
I opened a PR against your branch that makes the existing specs pass again: https://github.com/mscottford/tree-view/pull/1

**Comment by mscottford** [comment]
Thanks @thedaniel!

**Comment by mscottford** [comment]
I'm getting an odd error when I try to use this branch via `apm link`. 

screenshot 2015-01-13 21 18 05


@thedaniel  Any thoughts for how to work around it? I've tried googling (unless my google-fu needs some work), and I've tried running `apm update`.

**Comment by kevinsawicki** [comment]
Try `apm rebuild`

**Comment by mscottford** [comment]
That did the trick. Thanks!

**Comment by mscottford** [comment]
Specs have been added. Please let me know if there's anything else that needs to be wrapped up to make this merge-able.

**Comment by thedaniel** [comment]
I'm generally pro this - any other comments from @atom/core?

**Comment by kevinsawicki** [comment]
I'm pro on this overall, I think the setting name could be improved though, the word `inline` throws me off a bit when trying to understand at first glance.

* `showFoldersBeforeFiles`
* `sortFoldersBeforeFiles`
* `showFilesAfterFolders`
* `sortFilesAfterFolders`

Any other ideas?

**Comment by thedaniel** [comment]
`groupFolders` | `groupDirectories` ?

**Comment by nathansobo** [comment]
I like @kevinsawicki's suggestion of `sortFoldersBeforeFiles`.

**Comment by mscottford** [comment]
`sortFoldersBeforeFiles` works for me. I think that would be much more clear. Naming things is hard. :)

**Comment by mscottford** [comment]
Name updated. Please take another peek, and let me know if there's anything else that needs to be addressed.

**Comment by thedaniel** [comment]
:+1: :ship:

**Comment by thedaniel** [comment]
This will be in Atom 0.177.0.

**Comment by jmeas** [comment]
@thedaniel, did this make it into 0.177.0? I'm not seeing the option.

Atom v0.177.0, tree-view v0.154.0

**Comment by kevinsawicki** [comment]
It should be in 0.177:

screen shot 2015-02-03 at 1 19 30 pm

**Comment by mscottford** [comment]
@jmeas It's there, but you have to pull up the settings for the tree-view package to find it.

1. From settings, click on Packages
2. Search for tree-view
3. Click the Settings button in the tree view search result
4. You should see something similar to the screenshot that @kevinsawicki posted.

**Comment by jmeas** [comment]
Yup, I'm familiar with adjusting package settings. It's just not there!

 

:open_mouth:

**Comment by mscottford** [comment]
Looks like the package is disabled. I wonder if that could be why.

**Comment by jmeas** [comment]
> Looks like the package is disabled. I wonder if that could be why.

Ha, wow – so enabling it did nothing, but after enabling it and closing out/reopening Atom, the setting then decided to show up. Interesting!

Thanks for the help @mscottford :+1:

**Pull request merged**
