### PR TITLE
[WIP] Use atom.watchPath instead of PathWatcher

### PR DESCRIPTION
**Pull request by 50Wliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Replaces [pathwatcher](https://github.com/atom/node-pathwatcher) with [atom.watchPath](https://atom.io/docs/api/v1.24.0/PathWatcher).

### Alternate Designs

None.

### Benefits

A better watching library that doesn't lock files everywhere on Windows.

### Possible Drawbacks

TODO

### Applicable Issues

TODO

### CODE REVIEW

**Comment by daviwil** [comment]
AppVeyor still crashing...  Maybe try the `@atom/temp` package with this change?

**Comment by 50Wliu** [comment]
@daviwil not crashing; just specs failing.  I haven't started fixing specs yet.

**Comment by smashwilson** [comment]
One thing to be aware of - once tree-view is backed by `watchPath()`, parts of the emulated `"atom"` filesystem watcher in core won't work any more, because they use terrible hacks to pull these events from tree-view:

https://github.com/atom/atom/blob/204a5aa6950b44ab767e9beee450203b1e7b550c/src/path-watcher.js#L222-L259

I'm not sure what the best solution is there. We could eliminate the "atom" watcher backend, or we could find another way to emulate those events, or just miss them.

**Comment by 50Wliu** [comment]
Closing this as I don't feel like I have the necessary experience yet to make this work.

**Pull request closed without merging**
