### PR TITLE
:arrow_up: upgrade event-kit, minimatch and temp

### PR DESCRIPTION
**Pull request by bobintornado**
Upgrade event-kit, minimatch and temp

### CODE REVIEW

**Comment by 50Wliu** [comment]
Why?

**Comment by bobintornado** [comment]
Just based on feedback from https://david-dm.org/atom/tree-view
And thought later versions could bring in better stuff.

**Comment by 50Wliu** [comment]
If you don't have a concrete explanation for how this PR improves tree-view or fixes existing bugs, I'm sorry to say that it most likely will not be accepted.

**Comment by 50Wliu** [comment]
Closing as the only dependency left on this list is minimatch, which we can look into separately.

**Pull request closed without merging**
