### PR TITLE
Make 'Move in trash' more verbose on failure, add a note for Linux

### PR DESCRIPTION
**Pull request by Hyrrmadr**
Add an alert to warn the user when a file couldn't be moved to trash correctly instead of silently failing.

Add a note for Linux to ask the user to check if 'gvfs-trash' is installed (the command-line utility used by electron to move files to trash).

screenshot_2016-01-12_11-31-43

### CODE REVIEW

**Comment by lee-dohm** [comment]
I think this would be better implemented as a [notification](https://github.com/atom/notifications). Also, could you add a spec for this behavior?

**Comment by Hyrrmadr** [comment]
Thanks for your feedback! I followed your advice and implemented it as a notification.

screen shot 2016-01-14 at 16 05 28

Sorry for the lack of spec, I couldn't find a way to trigger the bug without `gvfs-trash` missing under Linux, but I figured a way now.

I also fixed a small 'bug' where atom would display the "Move to trash" confirm popup when trying to delete with no file selected (I deselected the current file with ⌘). I added a spec to test the behavior.

**Comment by lee-dohm** [comment]
One question on this ... what if I have 15 files selected and they all run into an error? Am I going to get 15 notifications?

**Comment by Hyrrmadr** [comment]
With these changes, yes.
Do you think I should make a single notification with the list of the failed deletions?
But it could be cumbersome too.

**Comment by lee-dohm** [comment]
Yes, it would be cumbersome. But I tend to see it as one failure rather than fifteen. Also, if it was 1015 instead of 15, I wouldn't want my editor thrown into some crazy notification loop or something.

I'd appreciate it if you could make the change. Thanks!

**Comment by Hyrrmadr** [comment]
I mean obviously you are right, one notification is better than 10 000. I was just wandering if there was any better solution. Maybe a way to collapse it like the exception notification.

Here is how it looks now:
screen shot 2016-01-14 at 22 59 16

**Comment by 50Wliu** [comment]
Should `gvfs-trash` just be made a dependency to install Atom so that we don't need the notification to install it?

**Comment by Hyrrmadr** [comment]
We could just remove the note in the notification about `gvfs-trash`, I just found it pretty frustrating that I couldn't remove anything in Atom because I was missing this package.
Anyway, I think it's a good idea to warn the user about a failure instead of just doing nothing, obviously it would be better if we had any idea why the deletion failed.

**Comment by lee-dohm** [comment]
I agree that this change is good to have rather than failing silently. We can have a separate issue or PR for the gvfs dependency.

**Comment by Hyrrmadr** [comment]
So, do you want me to remove the note about `gvfs-trash` ?

**Comment by lee-dohm** [comment]
@Hyrrmadr Thanks for the ping. No, I think the note about gvfs-trash is fine for now.

**Comment by 50Wliu** [comment]
@lee-dohm are changes still required for this PR?

**Comment by lee-dohm** [comment]
Thanks for this! And thanks for the ping @50Wliu :grinning:

**Pull request merged**
