### PR TITLE
rename file from tab

### PR DESCRIPTION
**Pull request by danielmurray**
Addresses feature requests

...atom/atom-11226
https://github.com/atom/atom/issues/11226

... and atom/tabs-251
https://github.com/atom/tabs/issues/251

### CODE REVIEW

**Comment by danielmurray** [comment]
@50Wliu does the `needs-testing` label means I need to write tests, or someone needs to validate that what I implemented does what is says it does?

**Comment by 50Wliu** [comment]
Someone needs to test your PR out.  I'll do so tonight!

**Comment by danielmurray** [comment]
Awesome! Looking forward to it!

**Comment by 50Wliu** [comment]
Just tested this out and I only see one small problem: attempting to rename an inactive tab doesn't work (eg there's no context menu option for that).  Though I noticed that `Reveal in Tree View` doesn't show up either.

Can you also clarify what the difference is between `.item-views` and `.tab-active`?  I'm guessing the latter is referring to the active tab, but I'm not too sure what the former is.

**Comment by danielmurray** [comment]
The former is the div defining the workspace of the file, however that feature is not defined the aforementioned tickets, so I will remove it.
As for not being able to edit the file name when not active, I figured this feature should be connected to the other tree-view function. If users request it then we can change it.

**Comment by danielmurray** [comment]
\

**Comment by danielmurray** [comment]
PR look good?

**Comment by 50Wliu** [comment]
Thanks!

**Pull request merged**
