### PR TITLE
file name filter as a service

### PR DESCRIPTION
**Pull request by monsterkodi**
Hello, I recently created a package to filter the tree view: [tree-view-filter](https://github.com/monsterkodi/tree-view-filter)
In my first attempt I just set the display style of the file entries to `none`.  
The problem with that approach is that the navigation with the keyboard doesn't work as expected: the hidden items still get keyboard focus.
I figured that i can't resolve this without some changes in the tree-view package itself.

With the changes in this pull request I could get the tree-view-filter package to work as expected without changing the current functionality of the tree-view. 

Please let me know If I you want me to change anything.

### CODE REVIEW

**Comment by monsterkodi** [comment]
P.S.: the branch [use_tree_view_service_to_filter_files](https://github.com/monsterkodi/tree-view-filter/tree/use_tree_view_service_to_filter_files) contains a version of the tree-view-filter that uses the new tree-view service

**Comment by monsterkodi** [comment]
Could someone please let me know if this has a chance of getting merged?
Any feedback is appreciated.
Thanks in advance.

**Comment by monsterkodi** [comment]
still needs review :)

**Comment by aphecetche** [comment]
Hi,

Any news about this one ? 

As a former user of XCode wanting to switch to Atom, I find myself in a position where I really miss(ed) the tree view live filter (plus the ability to list only the files with a git status, but that's another story...)

The current tree-view-filter package is indeed working expect for, as noted, that it's not 100% live (i.e. the not-expanded directories don't get the filter applied when you then expand them). 

Regards,

**Comment by tlnagy** [comment]
Hey @50Wliu, any chance that you or someone else could view these changes? This seems like it would be useful.

**Comment by monsterkodi** [comment]
Hello, 
I found a way to make the desired behaviour work without changes needed in the tree-view package. I still think that the solution in this PR is better (more general and less prone to break with future changes to the tree-view), but after two years I think its time for some hacks :-)

**Pull request closed without merging**
