### PR TITLE
Fix keybinding conflict with window:reset-font-size

### PR DESCRIPTION
**Pull request by mnquintana**
Fixes https://github.com/atom/tree-view/issues/251

### CODE REVIEW

**Comment by mnquintana** [comment]
@atom/feedback What do you think about the keybinding?

**Comment by lee-dohm** [comment]
I don't have a problem with it, though I am concerned about changing a default that has existed in Atom for over a year. This should be well documented and communicated.

**Comment by 50Wliu** [comment]
> I am concerned about changing a default that has existed in Atom for over a year

To be honest I don't think anyone on Windows/Linux really expected this behavior.  It's pretty universal to have <kbd>Ctrl+0</kbd> bound to resetting the zoom size.

**Comment by mnquintana** [comment]
Aside from the fact that the keybinding's changed, what do you think about the keybinding I chose to replace it? Does <kbd>Alt-0</kbd> seem reasonable / idiomatic for Win / Linux?

**Comment by lee-dohm** [comment]
It's been a few years since I've used Windows. I would typically think of <kbd>Tab</kbd> or <kbd>Ctrl+Tab</kbd> for moving around sub-views in Windows programs. I'd check to see if Visual Studio has some key binding for moving between the Tree View, Edit View and others.

**Comment by lee-dohm** [comment]
According to [this list of Visual Studio 2015 key shortcuts](http://visualstudioshortcuts.com/2015/) the "Next View" accelerator is <kbd>Ctrl+Page Down</kbd>. But if you look at the Team and Team Foundation sections, they use <kbd>Ctrl+0</kbd> as the beginning of a multi-key accelerator for lots of "switch to other views" things. <kbd>Alt+0</kbd> is used for a single, obscure function.

**Comment by ardrigh** [comment]
Tree View currently uses the following:

<kbd>Ctrl+\\</kbd> for `Toggle` 
<kbd>Ctrl+Shift+\\</kbd> for `Reveal Active File`

Would <kbd>Alt+\\</kbd> be a better key binding for `Focus` than <kbd>Alt+0</kbd>?

I can't see <kbd>Alt+\\</kbd> used for anything else, unless another package is using it

**Comment by mnquintana** [comment]
So after reviewing editors and IDEs on Windows, I've come to the conclusion that there is no consistent keybinding for this kind of behavior. So in this case, I'm going to go with whatever feels most intuitive for *Atom* users - I think the two candidates are <kbd>Alt+\</kbd> and <kbd>Alt+0</kbd>. The former preserves one key from the current keybinding, but the latter seems more consistent with other Tree View keybindings. What do people think about these two options?

**Comment by mnquintana** [comment]
Alright, the new keybinding is going to be <kbd>Alt-\</kbd> since it seems the most consistent with other Tree View keybindings. Thanks everyone for the feedback!

**Pull request merged**
