### PR TITLE
Fix squashed directories appearing duplicated when reloaded

### LINKED ISSUE #705: Multiplying copies of icons for symlinked directories with "Collapse directories" enabled
1. Create a project directory with a symlink within itself:

    ```
    mkdir ~/some-test-dir/ && cd ~/some-test-dir/
    mkdir -p foo/bar
    ln -s foo/bar bar
    atom . &
    ```

2. Enable "Collapse directories" in tree-view settings.

    atom_step1

3. Right-click `some-test-dir` project folder > New file, save as `testfile.txt`. Result: `testfile.txt` is created (expected), another icon for `foo/bar` also shows up beneath it (bug).

    atom_step2

4. Modify testfile.txt and save. Result: two more icons for `foo/bar` appear.

    atom_step3

5. Repeat step 4 as desired until number of `foo/bar`'s is comically large. Two new icons appear each time the file is saved.

On Atom 1.2.3, tree-view 0.195.0, Ubuntu 14.04 LTS

### PR DESCRIPTION
**Pull request by itiut**
Fixes #705 by not overwriting `@name` with nested directory name in `squashDirectoryNames`.

### CODE REVIEW

**Comment by mrfoto** [comment]
Can someone review this please? #705 is affecting my workflow quite drastically 😁 
cc @kuychaco @nathansobo

**Comment by nathansobo** [comment]
Hey, I see this. I'm dealing with a bunch of stuff at the moment but want to get to it because this bug is obviously pretty dumb.

**Comment by mrfoto** [comment]
@nathansobo Great, thanks.

I don't want to be annoying or anything, just don't want this to get lost 😃

**Comment by nathansobo** [comment]
Thanks @itiut for the fix. Apologies it sat for so long. Thanks @mrfoto for the ping. This should be out with Atom 1.11.x.

**Comment by mrfoto** [comment]
Awesome! Thanks @nathansobo and of course @itiut

**Pull request merged**
