### PR TITLE
Added a keybinding to rename the current buffer

### PR DESCRIPTION
**Pull request by laituan245**
This is for the issue: https://github.com/atom/atom/issues/3212
Thanks.

### CODE REVIEW

**Comment by mnquintana** [comment]
Thanks for contributing! This keybinding conflicts with [markdown-preview](https://github.com/atom/markdown-preview/blob/master/keymaps/markdown-preview.cson#L2), however, among others.

**Comment by laituan245** [comment]
Hi @mnquintana. Would ctrl-shift-r be ok ?

**Comment by laituan245** [comment]
Hi @mnquintana. I have changed the keybinding to "alt-shift-m". Would it be ok now ?

**Comment by damieng** [comment]
Windows keybinding for rename should be <kbd>F2</kbd>

**Comment by sass94** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Opt out please 


Sent from Yahoo Mail for iPhone


On Wednesday, April 5, 2017, 12:01 PM, Damien Guard <notifications@github.com> wrote:


Windows keybinding for rename should be F2

**Comment by damieng** [comment]
@sass94 only you can unsubscribe from a thread - the link is at the bottom of the email "Mute this thread"

**Comment by jurajpiar** [comment]
This seems to be already in place (windows) using F2.

**Comment by lee-dohm** [comment]
Looks like this has been fixed 👍

**Pull request closed without merging**
