### PR TITLE
🐛 Prevent files to be expanded

### PR DESCRIPTION
**Pull request by miguelcg**
### Description of the Change

Solves #921. Prevents files to be expanded (and therefore causing an error).
This PR is a copy of #970 but with a test scenario.

### Benefits

Solves #921

### Applicable Issues

#921

### CODE REVIEW

**Comment by 50Wliu** [comment]
It doesn't look like the spec properly covers this change.  Does it pass if you comment out that line?

**Comment by miguelcg** [comment]
You were right @50Wliu. If you commented the line it didn't work but for other reason. Now the test actually tests the right thing.
Let me know if there's anything pending to get this merged.

**Comment by miguelcg** [comment]
@50Wliu Is there anything pending from my side?

**Comment by 50Wliu** [comment]
Will take a look soon.

**Comment by miguelcg** [comment]
Thanks @50Wliu!

**Comment by 50Wliu** [comment]
I still think the test can be improved.  Here's what I have:
```coffee
describe "when trying to expand a file", ->
        it "doesn't expand the file and doesn't error", ->
          file = root1.find('.file:contains(tree-view.js)')[0]
          treeView.selectEntry(file)
          expect(file).not.toHaveClass 'expanded'

          expect(-> treeView.expandDirectory(true)).not.toThrow()
          expect(file).not.toHaveClass 'expanded'

          expect(-> treeView.expandDirectory(false)).not.toThrow()
          expect(file).not.toHaveClass 'expanded'
```
Now there's an explicit check to make sure that it doesn't throw.

**Comment by miguelcg** [comment]
Nice one @50Wliu! Can you commit the test? 😃

**Comment by 50Wliu** [comment]
Also, now the implementation differs from recursive-collapse-directory, which searches for the closest directory and collapses that.  What do you think about doing the same thing for recursive-expand-directory?

**Comment by miguelcg** [comment]
@50Wliu Actually I think that it should be the other way around. `recursive-collapse-directory` should recursively collapse the directories and not only collapse the closest one I reckon.
What do you think?

**Comment by miguelcg** [comment]
Finally AppVeyor check passing! Nice work @as-cii!

**Comment by 50Wliu** [comment]
Sorry, what I meant was that recursive-collapse-directory searches for the closest directory (not sure if this means the parent directory or not) if you execute it on a file, and then recursively collapses that directory.

**Pull request closed without merging**
