### PR TITLE
Copy files on drop if control is pressed

### LINKED ISSUE #703: Ctrl/Cmd-Drag and drop should copy the selected file / directory
Ctrl drag and drop in file tree does not create a copy of the file/directory (as it is in Visual Studio) instead it just moves the file.

### PR DESCRIPTION
**Pull request by 50Wliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

For consistency with OS behavior, copy files when dropping if control is pressed, rather than moving them.

### Alternate Designs

None?

### Benefits

Consistency with file managers such as Windows Explorer.

### Possible Drawbacks

Unknown

### Applicable Issues

Closes #703
Supersedes and closes #800

* [x] Make it work
  * [x] Add specs
* [x] Allow files to be copied to the same directory
  * [x] Add specs
* [ ] Regression testing

### CODE REVIEW

**Comment by Diesector** [comment]
I would love to get my hands on this to test, could I manually replace the spec/lib files to get this update?

**Comment by 50Wliu** [comment]
Verification checklist:
* [ ] Copy and pasting a file to the same directory pastes the file with a `0` behind the basename
* [ ] Cut and pasting a file to the same directory pastes the file (you should notice no change)
* [ ] Copy and pasting a directory to the same directory pastes the directory with a `0` appended (recursive copy)
* [ ] Cut and pasting a directory to the same directory pastes the directory (you should notice no change)
* [ ] Copy and pasting a file and directory to the same directory pastes both successfully, with numbers appended as appropriate
* [ ] Cut and pasting a file and directory to the same directory pastes both successfully (you should notice no change)
* [ ] Copy and pasting a file to a different directory pastes the file succesfully
* [ ] Cut and pasting a file to a different directory pastes the file successfully and removes the file from the original location
* [ ] Copy and pasting a directory to a different directory pastes the directory successfully
* [ ] Cut and pasting a directory to a different directory pastes the directory successfully
* [ ] Copy and pasting a file and directory to a different directory pastes both successfully
* [ ] Cut and pasting a file and directory to a different directory pastes both successfully

Now repeat the above with drag-and-drop (replacing "copy" with ctrl-drag, and "cut" with drag).

**Comment by UziTech** [comment]
It would be great to get this in the next version of atom along with the other multi-drag improvements 👍

**Comment by 50Wliu** [comment]
> Does that reflect the current status of things, or have you verified that everything is working?

@nathansobo I've verified that everything's working on Windows, but not on macOS or Linux.

**Comment by nathansobo** [comment]
@50Wliu It looks like the tests are hanging after merging in master. This seems to be due to a dialog prompt when pasting files that conflict with existing directory entries. Maybe something changed on master causing the prompt to be displayed in a situation where it wasn't previously. We'll kick this back to you, since you have more context. Please feel free to ping me again when you get a green build.

**Comment by 50Wliu** [comment]
Ugh, dialog prompts. I'm guessing something to do with #1180.

**Comment by 50Wliu** [comment]
@nathansobo All right, specs are 💚 again.

#### What was the problem?
In this PR, I extracted much of the logic in `pasteEntries` to the helper methods `copyEntry` and `moveEntry`. Simultaneously, in #1180, I updated `moveEntry` to show a dialog box on conflicting entries. Prior to this PR, `moveEntry` was _only_ used for drag-and-drop, and so the regular cut/paste specs were still expecting to error on conflicting entries. Now that all the move logic is centralized in one function, those specs began to hang due to the appearance of an unexpected dialog prompt.

#### The fix
I've essentially copied over all the specs I wrote in #1180 and adjusted them for the cut functions. Yes, that means we now have (almost) duplicate spec coverage for `moveEntry`, and we should probably rewrite those specs to remove the duplication. However, that would be out of the scope of this PR.

**Comment by nathansobo** [comment]
I've tested everything manually on macOS per your checklist. Since this all relies on Node APIs to interface with the file system and we have thorough test coverage, I'm going to skip testing on Linux because I can't see how things could be so different on that platform that this would be broken while still building green on Travis. Perhaps famous last words.

**Comment by nathansobo** [comment]
Thanks for your stewardship @50Wliu! ❤️ :zap:

**Comment by Dzemy** [comment]
Maybe change the icon when you holding control will be cool :) , i first think there is no way how to copy file.

**Pull request merged**
