### PR TITLE
Add drag & drop

### PR DESCRIPTION
**Pull request by saschagehlich**
This PR adds drag and drop functionality to the `tree-view` package.

tree-view-dnd

### CODE REVIEW

**Comment by polybuildr** [comment]
Must have feature. +1

**Comment by AveVlad** [comment]
+1

**Comment by theaqua** [comment]
What is the blocker for accept this PR?

**Comment by mnquintana** [comment]
@theaqua This PR is quite old and has merge conflicts. @saschagehlich Are you still interested in merging this PR? If so, would you mind fixing the merge conflicts?

**Comment by saschagehlich** [comment]
Rewriting this on top of master would require much less work than fixing the conflicts (since atom got a lot API changes since I filed this PR). But since I'm still very interested in this feature - I think I'm gonna put some work into this and create another PR later this or next week. 

@mnquintana Any hints on how to create tests for such a feature (which requires simulated mouse events)?

**Comment by mnquintana** [comment]
@saschagehlich Sure, sounds good!

I think in most specs I've seen for mouse stuff the events are just dispatched, but since this is testing drag-and-drop that would get kinda tricky... maybe mocking the drag event?

**Comment by saschagehlich** [comment]
@mnquintana Do you recall any atom package that does stuff like that already?

**Comment by mnquintana** [comment]
@saschagehlich Ah looks like tabs does it: https://github.com/atom/tabs/blob/master/spec/event-helpers.coffee

**Comment by saschagehlich** [comment]
@mnquintana Great, I think I can work with this. Thanks :)

**Comment by kevinsawicki** [comment]
@mnquintana and @saschagehlich thanks for getting the conversation going on this again, would be great to get this in this time, apologies for not reviewing it and moving it forward sooner.

**Comment by mnquintana** [comment]
Btw @saschagehlich and @kevinsawicki, there was also https://github.com/atom/tree-view/pull/478 submitted for adding drag-and-drop using the HTML5 API (that one's also blocked pending changes though). What do you think about adopting that approach?

**Comment by saschagehlich** [comment]
IMO this totally makes sense and would save us a lot of code. Specs would be very light-weight as well - we could just fire the HTML5 drop events on the elements. I'll take a look at that!

**Comment by izuzak** [comment]
Gonna close this in favor of https://github.com/atom/tree-view/pull/543 which was already merged. Let me know if there's still a reason to keep this one open :panda_face:

**Comment by ioquatix** [comment]
Did this PR support dragging around multiple things?

**Pull request closed without merging**
