### PR TITLE
Improve behavior of TreeView::moveUp() with nested directories

### LINKED ISSUE #1261: Moving selection up using keyboard skips entries when sibling above has multiple levels of expanded children
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using the keyboard for navigating the tree structure, some selections are skipped when moving up. This happens specifically when the sibling above the current selection has more than 1 level of expanded children.

### Steps to Reproduce

1. Have a workspace with following (or similar) folder structure (all expanded):
> A
>> B
>>> C

> D
2. Select folder D with mouse or keyboard
3. Press keyboard 'Up' (or invoke Core: Move Up)

**Expected behavior:**
Selection moves to folder C

**Actual behavior:** 
Selection moves to folder B

**Reproduces how often:**
Every time

### Versions

$ atom --version
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 2.7.13
git 2.15.2

### Additional Information
See comment below for my 2 cents on a simple fix

### PR DESCRIPTION
**Pull request by synthetiv**
### Description of the Change

The previous moveUp() behavior checked whether the entry directly before the currently selected entry was an expanded directory, and if so, it selected the last child of that directory. That was perfectly fine for most cases, but if that last child entry was _also_ an expanded directory, the moveUp() command would simply select the child directory instead of selecting _its_ last entry. This pull request changes that behavior so that tree-view will recursively check whether the previous entry is an expanded directory, then check whether the last entry in that directory is too, and so on, before finally selecting the first entry it encounters that is either not a directory or not expanded.

### Alternate Designs

An earlier revision of this change didn't explicitly check whether previousEntry was a directory or was expanded, and it also called TreeView::selectEntry() with each recursive iteration. That didn't seem to break anything, but it probably wasn't a great idea.

### Benefits

Keyboard navigation of the tree-view will be a lot nicer, especially for users who have the "sort directories before files" option turned off.

### Possible Drawbacks

I can't foresee any.

### Applicable Issues

#1020 
Fixes #1261

### CODE REVIEW

**Comment by synthetiv** [comment]
Hi, @50Wliu – let me know if/when there's anything I should change. It wasn't obvious to me whether or not the failed beta build was related to my edits.

Thanks!

**Comment by 50Wliu** [comment]
If/when I review this I'll tell you :).  It's not obvious to me whether or not the Appveyor failure is related to this PR (doesn't look like it), so I've restarted the build just in case.

**Comment by synthetiv** [comment]
This merges cleanly with master, and based on my limited user testing I'd say it's working fine, but for some reason I can't get the Jasmine tests to run at all (on *any* branch). Not sure if I'm running them wrong or if there's something wrong with the tests...

**Comment by lee-dohm** [comment]
@50Wliu can we help you with this?

**Comment by 50Wliu** [comment]
@synthetiv what do you think about the following diff?
```diff
diff --git a/lib/tree-view.coffee b/lib/tree-view.coffee
index d72b91e..d9855cf 100644
--- a/lib/tree-view.coffee
+++ b/lib/tree-view.coffee
@@ -421,8 +421,6 @@ class TreeView
     selectedEntry = @selectedEntry()
     if selectedEntry?
       if previousEntry = @previousEntry(selectedEntry)
-        while previousEntry.classList.contains('directory', 'expanded') and previousEntry.entries.children.length > 0
-          previousEntry = _.last(previousEntry.entries.children)
         @selectEntry(previousEntry)
       else
         @selectEntry(selectedEntry.parentElement.closest('.directory'))
@@ -445,12 +443,21 @@ class TreeView
     return null
 
   previousEntry: (entry) ->
-    currentEntry = entry
-    while currentEntry?
-      currentEntry = currentEntry.previousSibling
-      if currentEntry?.matches('.entry')
-        return currentEntry
-    return null
+    previousEntry = entry.previousSibling
+    while previousEntry? and not previousEntry.matches('.entry')
+      previousEntry = previousEntry.previousSibling
+
+    return null unless previousEntry?
+
+    # If the previous entry is an expanded directory,
+    # we need to select the last entry in that directory,
+    # not the directory itself
+    if previousEntry.matches('.directory.expanded')
+      entries = previousEntry.querySelectorAll('.entry')
+      if entries.length > 0
+        return entries[entries.length - 1]
+
+    return previousEntry
 
   expandDirectory: (isRecursive=false) ->
     selectedEntry = @selectedEntry()
```

This adjusts the `previousEntry` method itself instead of working around it in `moveUp`.

In addition, can you add a test for the case when there is an expanded directory that contains no children entries?

**Comment by 50Wliu** [comment]
Hey @synthetiv, just checking in!  If you're busy, I can push a commit to your fork applying that diff and adding the test.

**Comment by JK-mber** [comment]
Hey @synthetiv and @50Wliu, any news on this one? I'm not sure what's still needed, but I'm keen to help where I can - I'm annoyed by this issue multiple times a day :smile:

**Pull request merged**
